# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secrets', '0002_auto_20180224_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('the_secret', models.CharField(max_length=255)),
                ('likes', models.ManyToManyField(related_name='liked_secret', to='secrets.User')),
                ('the_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='secrets.User')),
            ],
        ),
    ]
