# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_secret_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='liked_by_this_user',
            field=models.BooleanField(default=False),
        ),
    ]
